-- 프로그래머스 SQL 고득점 Kit
-- 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE)
FROM ANIMAL_INS 
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE

-- 동명 동물 수 찾기
SELECT NAME, COUNT(NAME)
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) > 1
ORDER BY NAME

-- 입양 시각 구하기(1)
SELECT HOUR(DATETIME) as HOUR, count(HOUR(DATETIME)) as COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR > 8 and HOUR < 20
ORDER BY HOUR

-- 입양 시각 구하기(2)
SET @hour := -1;
SELECT (@hour := @hour + 1) as HOUR, (SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @hour) as COUNT
FROM ANIMAL_OUTS
WHERE @hour < 23;